/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cellule` | `/cellule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contact` | `/contact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mes-signalements` | `/mes-signalements`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/numeros` | `/numeros`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/signalement` | `/signalement`; params?: Router.UnknownInputParams; } | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cellule` | `/cellule`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/contact` | `/contact`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mes-signalements` | `/mes-signalements`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/numeros` | `/numeros`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/signalement` | `/signalement`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cellule${`?${string}` | `#${string}` | ''}` | `/cellule${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/contact${`?${string}` | `#${string}` | ''}` | `/contact${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mes-signalements${`?${string}` | `#${string}` | ''}` | `/mes-signalements${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/numeros${`?${string}` | `#${string}` | ''}` | `/numeros${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/signalement${`?${string}` | `#${string}` | ''}` | `/signalement${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cellule` | `/cellule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contact` | `/contact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mes-signalements` | `/mes-signalements`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/numeros` | `/numeros`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/signalement` | `/signalement`; params?: Router.UnknownInputParams; } | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
